---
- hosts: local
  connection: local
  become: yes

  pre_tasks:

  - name: install packages required by docker
    become: true
    apt:
      update_cache: yes
      state: latest
      name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gpg-agent
      - software-properties-common #One day
  
  tasks:
    
    - name: Print the gateway for each host when defined
      ansible.builtin.debug:
        msg: "System {{BACK_HOST}} "

  