---
- hosts: local
  connection: local
  become: yes

  vars:
    BACK_HOST_VAR: aaaaa

  pre_tasks:

  - name: Set environment variables for project
    set_fact: 
      BACK_HOST: "{{ BACK_HOST }}"
  
  - name: Update and upgrade apt packages
    become: true
    apt:
      upgrade: "yes"
      update_cache: yes
      cache_valid_time: 86400 #One day
  
  tasks:

    - name: Install the nodejs
      apt:
        name: nodejs
        state: present

    - name: Install NPM
      apt:
        name: npm
        state: present

    - name: install pm2
      npm:
        name: pm2
        global: yes
        state: present   

    - name: Clone the repository
      git:
        repo: https://github.com/andresbelo12/movie-analyst-ui.git
        dest: ""

    - name: Install npm packages 
      npm: 
        path: /movie-analyst-ui
        executable: /usr/bin/npm

    - name: Delete old pm2 process
      command: pm2 delete ui
      ignore_errors: yes

    - name: Start pm2
      command: pm2 start /movie-analyst-ui/server.js --name ui
    
    - name: nada
      shell: "echo $BACK_HOST && pm2 status"

    