---
- hosts: local
  connection: local
  become: yes

  pre_tasks:

  - name: Update and upgrade apt packages
    become: true
    apt:
      upgrade: "yes"
      update_cache: yes
      cache_valid_time: 86400 #One day
  
  tasks:

    - name: Install docker
      apt:
        name:  docker.io
        state: present

    - name: Start docker service
      service:
        name: docker
        state: started

    - name: Clone the repository
      git:
        repo: https://github.com/andresbelo12/movie-analyst-ui.git
        dest: "/movie-analyst-ui"
    
    - name: Build an image and push
      docker_image:
        build:
          path: /movie-analyst-ui
        name: ui
        tag: v1
        force_source: yes
        push: yes
        source: build
      delegate_to: 127.0.0.1
      become: no  

    - name: Create container
      docker_container:
        name: ui
        image: movie-analyst-ui/ui:v1
        state: started
        recreate: yes
        published_ports:
          - "3030:3030"
    
    
    